---
engines:
  # Enable Lizard code analysis
  lizard:
    enabled: true

  # Enable only cppcheck for C code analysis
  cppcheck:
    enabled: true

  # Enable Semgrep for security analysis
  semgrep:
    enabled: true

# Exclude build and temporary directories
exclude_paths:
  - "build/**"
  - "bin/**"
  - ".cache/**"
  - ".makepkg/**"
  - "pkg/**"
  - "temp/**"
  - "*.pkg.*"
  - "coolerdash-*.pkg.*"
